// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internode.proto

package protocolconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	protocol "github.com/river-build/river/core/node/protocol"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeToNodeName is the fully-qualified name of the NodeToNode service.
	NodeToNodeName = "river.NodeToNode"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeToNodeAllocateStreamProcedure is the fully-qualified name of the NodeToNode's AllocateStream
	// RPC.
	NodeToNodeAllocateStreamProcedure = "/river.NodeToNode/AllocateStream"
	// NodeToNodeNewEventReceivedProcedure is the fully-qualified name of the NodeToNode's
	// NewEventReceived RPC.
	NodeToNodeNewEventReceivedProcedure = "/river.NodeToNode/NewEventReceived"
	// NodeToNodeNewEventInPoolProcedure is the fully-qualified name of the NodeToNode's NewEventInPool
	// RPC.
	NodeToNodeNewEventInPoolProcedure = "/river.NodeToNode/NewEventInPool"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	nodeToNodeServiceDescriptor                = protocol.File_internode_proto.Services().ByName("NodeToNode")
	nodeToNodeAllocateStreamMethodDescriptor   = nodeToNodeServiceDescriptor.Methods().ByName("AllocateStream")
	nodeToNodeNewEventReceivedMethodDescriptor = nodeToNodeServiceDescriptor.Methods().ByName("NewEventReceived")
	nodeToNodeNewEventInPoolMethodDescriptor   = nodeToNodeServiceDescriptor.Methods().ByName("NewEventInPool")
)

// NodeToNodeClient is a client for the river.NodeToNode service.
type NodeToNodeClient interface {
	AllocateStream(context.Context, *connect.Request[protocol.AllocateStreamRequest]) (*connect.Response[protocol.AllocateStreamResponse], error)
	NewEventReceived(context.Context, *connect.Request[protocol.NewEventReceivedRequest]) (*connect.Response[protocol.NewEventReceivedResponse], error)
	NewEventInPool(context.Context, *connect.Request[protocol.NewEventInPoolRequest]) (*connect.Response[protocol.NewEventInPoolResponse], error)
}

// NewNodeToNodeClient constructs a client for the river.NodeToNode service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeToNodeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeToNodeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &nodeToNodeClient{
		allocateStream: connect.NewClient[protocol.AllocateStreamRequest, protocol.AllocateStreamResponse](
			httpClient,
			baseURL+NodeToNodeAllocateStreamProcedure,
			connect.WithSchema(nodeToNodeAllocateStreamMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		newEventReceived: connect.NewClient[protocol.NewEventReceivedRequest, protocol.NewEventReceivedResponse](
			httpClient,
			baseURL+NodeToNodeNewEventReceivedProcedure,
			connect.WithSchema(nodeToNodeNewEventReceivedMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		newEventInPool: connect.NewClient[protocol.NewEventInPoolRequest, protocol.NewEventInPoolResponse](
			httpClient,
			baseURL+NodeToNodeNewEventInPoolProcedure,
			connect.WithSchema(nodeToNodeNewEventInPoolMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeToNodeClient implements NodeToNodeClient.
type nodeToNodeClient struct {
	allocateStream   *connect.Client[protocol.AllocateStreamRequest, protocol.AllocateStreamResponse]
	newEventReceived *connect.Client[protocol.NewEventReceivedRequest, protocol.NewEventReceivedResponse]
	newEventInPool   *connect.Client[protocol.NewEventInPoolRequest, protocol.NewEventInPoolResponse]
}

// AllocateStream calls river.NodeToNode.AllocateStream.
func (c *nodeToNodeClient) AllocateStream(ctx context.Context, req *connect.Request[protocol.AllocateStreamRequest]) (*connect.Response[protocol.AllocateStreamResponse], error) {
	return c.allocateStream.CallUnary(ctx, req)
}

// NewEventReceived calls river.NodeToNode.NewEventReceived.
func (c *nodeToNodeClient) NewEventReceived(ctx context.Context, req *connect.Request[protocol.NewEventReceivedRequest]) (*connect.Response[protocol.NewEventReceivedResponse], error) {
	return c.newEventReceived.CallUnary(ctx, req)
}

// NewEventInPool calls river.NodeToNode.NewEventInPool.
func (c *nodeToNodeClient) NewEventInPool(ctx context.Context, req *connect.Request[protocol.NewEventInPoolRequest]) (*connect.Response[protocol.NewEventInPoolResponse], error) {
	return c.newEventInPool.CallUnary(ctx, req)
}

// NodeToNodeHandler is an implementation of the river.NodeToNode service.
type NodeToNodeHandler interface {
	AllocateStream(context.Context, *connect.Request[protocol.AllocateStreamRequest]) (*connect.Response[protocol.AllocateStreamResponse], error)
	NewEventReceived(context.Context, *connect.Request[protocol.NewEventReceivedRequest]) (*connect.Response[protocol.NewEventReceivedResponse], error)
	NewEventInPool(context.Context, *connect.Request[protocol.NewEventInPoolRequest]) (*connect.Response[protocol.NewEventInPoolResponse], error)
}

// NewNodeToNodeHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeToNodeHandler(svc NodeToNodeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeToNodeAllocateStreamHandler := connect.NewUnaryHandler(
		NodeToNodeAllocateStreamProcedure,
		svc.AllocateStream,
		connect.WithSchema(nodeToNodeAllocateStreamMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	nodeToNodeNewEventReceivedHandler := connect.NewUnaryHandler(
		NodeToNodeNewEventReceivedProcedure,
		svc.NewEventReceived,
		connect.WithSchema(nodeToNodeNewEventReceivedMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	nodeToNodeNewEventInPoolHandler := connect.NewUnaryHandler(
		NodeToNodeNewEventInPoolProcedure,
		svc.NewEventInPool,
		connect.WithSchema(nodeToNodeNewEventInPoolMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/river.NodeToNode/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeToNodeAllocateStreamProcedure:
			nodeToNodeAllocateStreamHandler.ServeHTTP(w, r)
		case NodeToNodeNewEventReceivedProcedure:
			nodeToNodeNewEventReceivedHandler.ServeHTTP(w, r)
		case NodeToNodeNewEventInPoolProcedure:
			nodeToNodeNewEventInPoolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeToNodeHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeToNodeHandler struct{}

func (UnimplementedNodeToNodeHandler) AllocateStream(context.Context, *connect.Request[protocol.AllocateStreamRequest]) (*connect.Response[protocol.AllocateStreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("river.NodeToNode.AllocateStream is not implemented"))
}

func (UnimplementedNodeToNodeHandler) NewEventReceived(context.Context, *connect.Request[protocol.NewEventReceivedRequest]) (*connect.Response[protocol.NewEventReceivedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("river.NodeToNode.NewEventReceived is not implemented"))
}

func (UnimplementedNodeToNodeHandler) NewEventInPool(context.Context, *connect.Request[protocol.NewEventInPoolRequest]) (*connect.Response[protocol.NewEventInPoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("river.NodeToNode.NewEventInPool is not implemented"))
}
