# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
tone_instructions: 'Be very concise and to the point'
early_access: true
enable_free_tier: true
reviews:
    profile: 'chill'
    request_changes_workflow: false
    high_level_summary: false
    review_status: false
    poem: false
    collapse_walkthrough: false
    sequence_diagrams: false
    path_filters: ['!packages/generated/**']
    auto_review:
        enabled: true
        drafts: false
        ignore_title_keywords:
            - 'NOAI'
chat:
    auto_reply: true
