name = "merkle-worker"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[r2_buckets]]
binding = "MERKLE_OBJECTS_R2"
bucket_name = "merkle-objects"

# The necessary secrets are:
# AUTH_SECRET (for paymaster proxy api)
# ADMIN_AUTH_SECRET (for admin api)
#
#
# for local development, you can add these in .dev.vars
# OR
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# add your secret property names here
#
# AUTH_SECRET


# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true


# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
[env.alpha]
r2_buckets = [
    { binding = "MERKLE_OBJECTS_R2", bucket_name = "merkle-objects-alpha" },
]

routes = [{ pattern = "merkle-worker-alpha.river.build", custom_domain = true }]
vars = { ENVIRONMENT = "alpha" }

[env.gamma]
r2_buckets = [
    { binding = "MERKLE_OBJECTS_R2", bucket_name = "merkle-objects-gamma" },
]

routes = [{ pattern = "merkle-worker-gamma.river.build", custom_domain = true }]
vars = { ENVIRONMENT = "gamma" }

[env.omega]
r2_buckets = [
    { binding = "MERKLE_OBJECTS_R2", bucket_name = "merkle-objects-omega" },
]
routes = [{ pattern = "merkle-worker.river.build", custom_domain = true }]
vars = { ENVIRONMENT = "omega" }
