# For running server in info mode ('info' command)
port: 4040
disableHttps: true

# Log info and above to console in text format
log:
    file: ''
    level: info
    console: true
    noColor: false
    format: text

debugEndpoints:
    pprof: true

# Notifications setting when node is run in notification mode
notifications:
  simulate: true
  subscription_expiration_duration: 720h
  authentication:
    sessionToken:
      lifetime: 15m
      key:
        algorithm: HS256
        key: c69b1973792ad59bebb96a2ab1639aafc0c1e229a1c2138d91834f0f6953a544
