# For running server in info mode ('info' command)
port: 4040
disableHttps: true

# Log info and above to console in text format
log:
    file: ''
    level: info
    console: true
    noColor: false
    format: text

debugEndpoints:
    pprof: true
