# For running server in info mode ('info' command)
port: 4040
useHttps: false

# Blockchain configuration
baseChain:
    chainId: 84532
    networkUrl: 'https://sepolia.base.org'
    blockTimeMs: 2000
riverChain:
    chainId: 6524490
    networkUrl: 'https://devnet.rpc.river.build'
    blockTimeMs: 2000

# Base contracts
architectContract:
    address: '0x8B7f2CA1f83b8318b0e7ad951af143f9DE90384F'

# River contracts
registryContract:
    address: '0xD85bB9e2CEcdA2b8Bf39aBcb514C222046029951'

# Disable logging
log:
    file: ''
    level: info
    console: true
    noColor: false
    format: text
