# For running server in info mode ('info' command)
port: 4040
useHttps: false

# Blockchain configuration
baseChain:
    chainId: 84532
    networkUrl: 'https://sepolia.base.org'
    blockTimeMs: 2000
riverChain:
    chainId: 6524490
    networkUrl: 'https://devnet.rpc.river.build'
    blockTimeMs: 2000

# Base contracts
architectContract:
    address: '0xc09ac0ffeecaae5100158247512dc177aeaca3e3'

# River contracts
registryContract:
    address: '0x44354786eacbebf981453a05728e1653bc3c5def'

# Disable logging
log:
    file: ''
    level: info
    console: true
    noColor: false
    format: text
# For reference:
# Space: 0xB712844A05245fBD17dADA91615C7c9521985873
# SpaceOwner: 0x0443258849016da8Af08e2984Bce8C0ef6Cfc9A0
# SpaceFactory: 0xc09ac0ffeecaae5100158247512dc177aeaca3e3
# BaseRegistry: 0x0230a9d28bc48a90d6f5e5112b24319ec1b14c52
# RiverRegistry: 0x44354786eacbebf981453a05728e1653bc3c5def
