name: Workitem (team members only)
description: Workitem for River project
title: "[WORKITEM] "
labels: ["workitem", "triage"]
projects: ["river-build/1"]
body:
- type: textarea
  attributes:
    label: Description
    description: Workitem details (supports markdown)
    render: markdown
  validations:
    required: false
