[package]
name = "mls-lib"
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
river-mls = {workspace = true}
river-mls-protocol = {workspace = true}
prost = {workspace = true}
libc = "0.2"

[build-dependencies]
cbindgen = "0.27.0"