DROP TABLE IF EXISTS userpreferences;
DROP TABLE IF EXISTS spaces;
DROP TABLE IF EXISTS channels;
DROP INDEX IF EXISTS WEB_SUB_USER_ID_IDX;
DROP TABLE IF EXISTS webpushsubscriptions;
DROP INDEX IF EXISTS APN_SUB_USER_ID_IDX;
DROP TABLE IF EXISTS apnpushsubscriptions;
DROP TABLE IF EXISTS singlenodekey;
