package testutils

import (
	"bytes"
	"regexp"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"

	"github.com/river-build/river/core/node/logging"
)

// RemoveJsonTimestamp removes the "time" field from a JSON log line generated by zap.
func RemoveJsonTimestamp(logOutput string) string {
	// Remove "time" field from output
	re := regexp.MustCompile(`\"timestamp\":\"[^\"]*\",`)
	return string(re.ReplaceAllString(logOutput, `"timestamp":"[TIMESTAMP]",`))
}

func ZapJsonLogger() (*zap.SugaredLogger, *bytes.Buffer) {
	buffer := &bytes.Buffer{}

	return zap.New(
		zapcore.NewCore(
			zapcore.NewJSONEncoder(logging.DefaultZapEncoderConfig()),
			zapcore.AddSync(buffer),
			zapcore.DebugLevel,
		),
	).Sugar(), buffer
}
