// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: internode.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiniblockProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes            [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	NewMiniblockNum   int64    `protobuf:"varint,2,opt,name=new_miniblock_num,json=newMiniblockNum,proto3" json:"new_miniblock_num,omitempty"`
	PrevMiniblockHash []byte   `protobuf:"bytes,3,opt,name=prev_miniblock_hash,json=prevMiniblockHash,proto3" json:"prev_miniblock_hash,omitempty"`
	ShouldSnapshot    bool     `protobuf:"varint,4,opt,name=should_snapshot,json=shouldSnapshot,proto3" json:"should_snapshot,omitempty"`
}

func (x *MiniblockProposal) Reset() {
	*x = MiniblockProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiniblockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniblockProposal) ProtoMessage() {}

func (x *MiniblockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniblockProposal.ProtoReflect.Descriptor instead.
func (*MiniblockProposal) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{0}
}

func (x *MiniblockProposal) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *MiniblockProposal) GetNewMiniblockNum() int64 {
	if x != nil {
		return x.NewMiniblockNum
	}
	return 0
}

func (x *MiniblockProposal) GetPrevMiniblockHash() []byte {
	if x != nil {
		return x.PrevMiniblockHash
	}
	return nil
}

func (x *MiniblockProposal) GetShouldSnapshot() bool {
	if x != nil {
		return x.ShouldSnapshot
	}
	return false
}

type AllocateStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Miniblock *Miniblock `protobuf:"bytes,1,opt,name=miniblock,proto3" json:"miniblock,omitempty"`
	StreamId  []byte     `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // stream_id should match the stream_id in the inception payload of the first event
}

func (x *AllocateStreamRequest) Reset() {
	*x = AllocateStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStreamRequest) ProtoMessage() {}

func (x *AllocateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStreamRequest.ProtoReflect.Descriptor instead.
func (*AllocateStreamRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateStreamRequest) GetMiniblock() *Miniblock {
	if x != nil {
		return x.Miniblock
	}
	return nil
}

func (x *AllocateStreamRequest) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type AllocateStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncCookie *SyncCookie `protobuf:"bytes,1,opt,name=sync_cookie,json=syncCookie,proto3" json:"sync_cookie,omitempty"`
}

func (x *AllocateStreamResponse) Reset() {
	*x = AllocateStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStreamResponse) ProtoMessage() {}

func (x *AllocateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStreamResponse.ProtoReflect.Descriptor instead.
func (*AllocateStreamResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateStreamResponse) GetSyncCookie() *SyncCookie {
	if x != nil {
		return x.SyncCookie
	}
	return nil
}

type NewEventReceivedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId []byte    `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Event    *Envelope `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// event.hash signed by node private key.
	NodeSig []byte `protobuf:"bytes,3,opt,name=node_sig,json=nodeSig,proto3" json:"node_sig,omitempty"`
}

func (x *NewEventReceivedRequest) Reset() {
	*x = NewEventReceivedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventReceivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventReceivedRequest) ProtoMessage() {}

func (x *NewEventReceivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventReceivedRequest.ProtoReflect.Descriptor instead.
func (*NewEventReceivedRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{3}
}

func (x *NewEventReceivedRequest) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *NewEventReceivedRequest) GetEvent() *Envelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NewEventReceivedRequest) GetNodeSig() []byte {
	if x != nil {
		return x.NodeSig
	}
	return nil
}

type NewEventReceivedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEventReceivedResponse) Reset() {
	*x = NewEventReceivedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventReceivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventReceivedResponse) ProtoMessage() {}

func (x *NewEventReceivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventReceivedResponse.ProtoReflect.Descriptor instead.
func (*NewEventReceivedResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{4}
}

type NewEventInPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *NewEventInPoolRequest) Reset() {
	*x = NewEventInPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventInPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventInPoolRequest) ProtoMessage() {}

func (x *NewEventInPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventInPoolRequest.ProtoReflect.Descriptor instead.
func (*NewEventInPoolRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{5}
}

func (x *NewEventInPoolRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type NewEventInPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEventInPoolResponse) Reset() {
	*x = NewEventInPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEventInPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventInPoolResponse) ProtoMessage() {}

func (x *NewEventInPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventInPoolResponse.ProtoReflect.Descriptor instead.
func (*NewEventInPoolResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{6}
}

type ProposeMiniblockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId           []byte   `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	DebugForceSnapshot bool     `protobuf:"varint,2,opt,name=debug_force_snapshot,json=debugForceSnapshot,proto3" json:"debug_force_snapshot,omitempty"`
	NewMiniblockNum    int64    `protobuf:"varint,3,opt,name=new_miniblock_num,json=newMiniblockNum,proto3" json:"new_miniblock_num,omitempty"`
	PrevMiniblockHash  []byte   `protobuf:"bytes,4,opt,name=prev_miniblock_hash,json=prevMiniblockHash,proto3" json:"prev_miniblock_hash,omitempty"`
	LocalEventHashes   [][]byte `protobuf:"bytes,5,rep,name=local_event_hashes,json=localEventHashes,proto3" json:"local_event_hashes,omitempty"`
}

func (x *ProposeMiniblockRequest) Reset() {
	*x = ProposeMiniblockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposeMiniblockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeMiniblockRequest) ProtoMessage() {}

func (x *ProposeMiniblockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeMiniblockRequest.ProtoReflect.Descriptor instead.
func (*ProposeMiniblockRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{7}
}

func (x *ProposeMiniblockRequest) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *ProposeMiniblockRequest) GetDebugForceSnapshot() bool {
	if x != nil {
		return x.DebugForceSnapshot
	}
	return false
}

func (x *ProposeMiniblockRequest) GetNewMiniblockNum() int64 {
	if x != nil {
		return x.NewMiniblockNum
	}
	return 0
}

func (x *ProposeMiniblockRequest) GetPrevMiniblockHash() []byte {
	if x != nil {
		return x.PrevMiniblockHash
	}
	return nil
}

func (x *ProposeMiniblockRequest) GetLocalEventHashes() [][]byte {
	if x != nil {
		return x.LocalEventHashes
	}
	return nil
}

type ProposeMiniblockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proposal      *MiniblockProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	MissingEvents []*Envelope        `protobuf:"bytes,2,rep,name=missing_events,json=missingEvents,proto3" json:"missing_events,omitempty"`
}

func (x *ProposeMiniblockResponse) Reset() {
	*x = ProposeMiniblockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposeMiniblockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeMiniblockResponse) ProtoMessage() {}

func (x *ProposeMiniblockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeMiniblockResponse.ProtoReflect.Descriptor instead.
func (*ProposeMiniblockResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{8}
}

func (x *ProposeMiniblockResponse) GetProposal() *MiniblockProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *ProposeMiniblockResponse) GetMissingEvents() []*Envelope {
	if x != nil {
		return x.MissingEvents
	}
	return nil
}

type SaveMiniblockCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId  []byte     `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Miniblock *Miniblock `protobuf:"bytes,2,opt,name=miniblock,proto3" json:"miniblock,omitempty"`
}

func (x *SaveMiniblockCandidateRequest) Reset() {
	*x = SaveMiniblockCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMiniblockCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMiniblockCandidateRequest) ProtoMessage() {}

func (x *SaveMiniblockCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMiniblockCandidateRequest.ProtoReflect.Descriptor instead.
func (*SaveMiniblockCandidateRequest) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{9}
}

func (x *SaveMiniblockCandidateRequest) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *SaveMiniblockCandidateRequest) GetMiniblock() *Miniblock {
	if x != nil {
		return x.Miniblock
	}
	return nil
}

type SaveMiniblockCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveMiniblockCandidateResponse) Reset() {
	*x = SaveMiniblockCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internode_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMiniblockCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMiniblockCandidateResponse) ProtoMessage() {}

func (x *SaveMiniblockCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internode_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMiniblockCandidateResponse.ProtoReflect.Descriptor instead.
func (*SaveMiniblockCandidateResponse) Descriptor() ([]byte, []int) {
	return file_internode_proto_rawDescGZIP(), []int{10}
}

var File_internode_proto protoreflect.FileDescriptor

var file_internode_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x72, 0x69, 0x76, 0x65, 0x72, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x11, 0x4d, 0x69, 0x6e,
	0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x69,
	0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e,
	0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x70, 0x72, 0x65, 0x76, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x68, 0x6f,
	0x75, 0x6c, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x64, 0x0a, 0x15, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e,
	0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x69, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x4c, 0x0a, 0x16, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x73,
	0x79, 0x6e, 0x63, 0x5f, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x52, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x22,
	0x78, 0x0a, 0x17, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x67, 0x22, 0x1a, 0x0a, 0x18, 0x4e, 0x65, 0x77,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0x18, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xf2, 0x01, 0x0a,
	0x17, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x66,
	0x6f, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x64, 0x65, 0x62, 0x75, 0x67, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x65, 0x77, 0x5f, 0x6d,
	0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x6d, 0x69, 0x6e, 0x69,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x11, 0x70, 0x72, 0x65, 0x76, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x10, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65,
	0x73, 0x22, 0x88, 0x01, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x69, 0x6e,
	0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x12, 0x36, 0x0a, 0x0e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x0d, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6c, 0x0a, 0x1d,
	0x53, 0x61, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x69,
	0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x09, 0x6d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x20, 0x0a, 0x1e, 0x53, 0x61,
	0x76, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbb, 0x03, 0x0a,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1c, 0x2e,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x4e, 0x65,
	0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x1e,
	0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x1c, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53,
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x4d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x77, 0x6e, 0x73, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x74, 0x6f, 0x77, 0x6e, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internode_proto_rawDescOnce sync.Once
	file_internode_proto_rawDescData = file_internode_proto_rawDesc
)

func file_internode_proto_rawDescGZIP() []byte {
	file_internode_proto_rawDescOnce.Do(func() {
		file_internode_proto_rawDescData = protoimpl.X.CompressGZIP(file_internode_proto_rawDescData)
	})
	return file_internode_proto_rawDescData
}

var file_internode_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internode_proto_goTypes = []interface{}{
	(*MiniblockProposal)(nil),              // 0: river.MiniblockProposal
	(*AllocateStreamRequest)(nil),          // 1: river.AllocateStreamRequest
	(*AllocateStreamResponse)(nil),         // 2: river.AllocateStreamResponse
	(*NewEventReceivedRequest)(nil),        // 3: river.NewEventReceivedRequest
	(*NewEventReceivedResponse)(nil),       // 4: river.NewEventReceivedResponse
	(*NewEventInPoolRequest)(nil),          // 5: river.NewEventInPoolRequest
	(*NewEventInPoolResponse)(nil),         // 6: river.NewEventInPoolResponse
	(*ProposeMiniblockRequest)(nil),        // 7: river.ProposeMiniblockRequest
	(*ProposeMiniblockResponse)(nil),       // 8: river.ProposeMiniblockResponse
	(*SaveMiniblockCandidateRequest)(nil),  // 9: river.SaveMiniblockCandidateRequest
	(*SaveMiniblockCandidateResponse)(nil), // 10: river.SaveMiniblockCandidateResponse
	(*Miniblock)(nil),                      // 11: river.Miniblock
	(*SyncCookie)(nil),                     // 12: river.SyncCookie
	(*Envelope)(nil),                       // 13: river.Envelope
}
var file_internode_proto_depIdxs = []int32{
	11, // 0: river.AllocateStreamRequest.miniblock:type_name -> river.Miniblock
	12, // 1: river.AllocateStreamResponse.sync_cookie:type_name -> river.SyncCookie
	13, // 2: river.NewEventReceivedRequest.event:type_name -> river.Envelope
	0,  // 3: river.ProposeMiniblockResponse.proposal:type_name -> river.MiniblockProposal
	13, // 4: river.ProposeMiniblockResponse.missing_events:type_name -> river.Envelope
	11, // 5: river.SaveMiniblockCandidateRequest.miniblock:type_name -> river.Miniblock
	1,  // 6: river.NodeToNode.AllocateStream:input_type -> river.AllocateStreamRequest
	3,  // 7: river.NodeToNode.NewEventReceived:input_type -> river.NewEventReceivedRequest
	5,  // 8: river.NodeToNode.NewEventInPool:input_type -> river.NewEventInPoolRequest
	7,  // 9: river.NodeToNode.ProposeMiniblock:input_type -> river.ProposeMiniblockRequest
	9,  // 10: river.NodeToNode.SaveMiniblockCandidate:input_type -> river.SaveMiniblockCandidateRequest
	2,  // 11: river.NodeToNode.AllocateStream:output_type -> river.AllocateStreamResponse
	4,  // 12: river.NodeToNode.NewEventReceived:output_type -> river.NewEventReceivedResponse
	6,  // 13: river.NodeToNode.NewEventInPool:output_type -> river.NewEventInPoolResponse
	8,  // 14: river.NodeToNode.ProposeMiniblock:output_type -> river.ProposeMiniblockResponse
	10, // 15: river.NodeToNode.SaveMiniblockCandidate:output_type -> river.SaveMiniblockCandidateResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internode_proto_init() }
func file_internode_proto_init() {
	if File_internode_proto != nil {
		return
	}
	file_protocol_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiniblockProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocateStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocateStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventReceivedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventReceivedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventInPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEventInPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposeMiniblockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposeMiniblockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMiniblockCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internode_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMiniblockCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internode_proto_goTypes,
		DependencyIndexes: file_internode_proto_depIdxs,
		MessageInfos:      file_internode_proto_msgTypes,
	}.Build()
	File_internode_proto = out.File
	file_internode_proto_rawDesc = nil
	file_internode_proto_goTypes = nil
	file_internode_proto_depIdxs = nil
}
