quiet: False
disable-version-string: True
with-expecter: False
dir: 'testutils/mocks'
filename: 'mock_{{.InterfaceNameSnake}}.go'
outpkg: 'mocks'
packages:
    github.com/towns-protocol/towns/core/node/nodes:
        interfaces:
            NodeRegistry:
            StreamRegistry:
    github.com/towns-protocol/towns/core/node/protocol/protocolconnect:
        interfaces:
            StreamServiceClient:
            NodeToNodeHandler:
