export function makeBotName(i: number): string {
    const adjectives = [
        'Speedy',
        'Mighty',
        'Blazing',
        'Radical',
        'Epic',
        'Awesome',
        'Crazy',
        'Insane',
        'Electric',
        'Fantastic',
        'Incredible',
        'Marvelous',
        'Spectacular',
        'Thrilling',
        'Dynamic',
        'Energetic',
        'Fierce',
        'Brave',
        'Bold',
        'Daring',
        'Courageous',
        'Valiant',
        'Gallant',
        'Heroic',
        'Intrepid',
        'Fearless',
        'Dauntless',
        'Audacious',
        'Tenacious',
    ]

    const nouns = [
        'Bolt',
        'Blaze',
        'Comet',
        'Dash',
        'Flash',
        'Laser',
        'Lightning',
        'Rocket',
        'Spark',
        'Storm',
        'Thunder',
        'Titan',
        'Vortex',
        'Whirlwind',
        'Avalanche',
        'Cyclone',
        'Earthquake',
        'Hurricane',
        'Meteor',
        'Supernova',
        'Tornado',
        'Tsunami',
        'Volcano',
        'Wildfire',
        'Zenith',
        'Beast',
        'Maverick',
        'Rogue',
        'Rebel',
        'Worker',
        'Reader',
        'Bee',
    ]

    const adjectiveIndex = i % adjectives.length
    const nounIndex = i % nouns.length

    const name = `${adjectives[adjectiveIndex]}${nouns[nounIndex]}${i}`
    return name
}
