services:
    stream-metadata:
        build:
            context: ../../
            dockerfile: ./packages/stream-metadata/Dockerfile
        environment:
            RIVER_ENV: alpha
            RIVER_CHAIN_RPC_URL: https://testnet.rpc.river.build/http
            PORT: 80
        ports:
            - 80:80
