#!/bin/bash


# Change to script's directory
cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"

# Array of directories to process
declare -a dirs=(
  "../packages/sdk/src"
  "../packages/react-sdk/src"
  "../packages/proto/src"
  )

# Loop through each directory
for dir in "${dirs[@]}"; do
  # Change directory to the target
  cd "$dir" || { echo "Directory $dir does not exist, skipping..."; continue; }

  # Initialize an empty array to store export statements
  declare -a exports
  exports=()

  # Add a fun comment at the top
  echo "/**************************************************************************" > index.ts
  echo " * This file can be auto generated by 🏕️ scripts/generate_sdk_index.sh 🏕️ *" >> index.ts
  echo " **************************************************************************/" >> index.ts

  # Loop through each TypeScript file to append an export statement to the array
  # Skip files that have ".test." in their name, the existing index.ts file, and directories
  for file in $(find . -type f \( -name "*.ts" -o -name "*.tsx" \) ! -name "*.test*" ! -name "*.d.ts" ! -name "index.ts" ! -path "*/tests/*" ! -path "*/internals/*" | sort); do
    # Remove the './' prefix and '.tsx' or '.ts' suffix from the file path
    file_without_slash=${file#./}
    file_without_tsx=${file_without_slash%.tsx}
    file_without_ts=${file_without_tsx%.ts}
    file=${file_without_ts}

    # Append export statement to the array
    exports+=("export * from './$file'")
  done

  echo "writing $dir/index.ts"

  # Append the sorted export statements to index.ts
  printf "%s\n" "${exports[@]}" >> index.ts

  # Change back to the original directory to continue the loop
  cd - || exit
done