version: '3.8'

volumes:
    prometheus_data: {}

services:
    river-metrics-discovery:
        container_name: river-metrics-discovery
        build:
            context: ../../
            dockerfile: ./packages/metrics-discovery/Dockerfile
        environment:
            - RIVER_RPC_URL=https://mainnet.rpc.river.build/http
            - ENV=omega
        volumes:
            - ./prometheus/etc/config:/river/packages/metrics-discovery/prometheus/etc/config:rw

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        user: root
        volumes:
            - ./prometheus/etc:/prometheus/etc
            - prometheus_data:/prometheus
        command:
            - --config.file=/prometheus/etc/config/prometheus-config.yaml
            - --log.level=debug
        ports:
            - '9090:9090'

    datadog:
        container_name: datadog
        image: datadog/agent:7
        ports:
            - '8125:8125/udp'
            - '8126:8126'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
            - ./datadog/prometheus.d:/conf.d/prometheus.d:ro
        environment:
            - DD_API_KEY=$DD_API_KEY
            - 'DD_APM_ENABLED=false'
