-- Alter CHAR(64) columns to be INLINE and UNCOMPRESSED
ALTER TABLE miniblock_candidates ALTER COLUMN stream_id SET STORAGE EXTENDED;
ALTER TABLE miniblock_candidates ALTER COLUMN block_hash SET STORAGE EXTENDED;

ALTER TABLE es ALTER COLUMN stream_id SET STORAGE EXTENDED;

ALTER TABLE miniblocks ALTER COLUMN stream_id SET STORAGE EXTENDED;

ALTER TABLE minipools ALTER COLUMN stream_id SET STORAGE EXTENDED;

-- Alter BYTEA columns to be UNCOMPRESSED
ALTER TABLE miniblock_candidates ALTER COLUMN blockdata SET STORAGE EXTENDED;

ALTER TABLE miniblocks ALTER COLUMN blockdata SET STORAGE EXTENDED;

ALTER TABLE minipools ALTER COLUMN envelope SET STORAGE EXTENDED;