-- Alter CHAR(64) columns to be INLINE and UNCOMPRESSED
ALTER TABLE miniblock_candidates ALTER COLUMN stream_id SET STORAGE DEFAULT;
ALTER TABLE miniblock_candidates ALTER COLUMN block_hash SET STORAGE DEFAULT;

ALTER TABLE es ALTER COLUMN stream_id SET STORAGE DEFAULT;

ALTER TABLE miniblocks ALTER COLUMN stream_id SET STORAGE DEFAULT;

ALTER TABLE minipools ALTER COLUMN stream_id SET STORAGE DEFAULT;

-- Alter BYTEA columns to be UNCOMPRESSED
ALTER TABLE miniblock_candidates ALTER COLUMN blockdata SET STORAGE DEFAULT;

ALTER TABLE miniblocks ALTER COLUMN blockdata SET STORAGE DEFAULT;

ALTER TABLE minipools ALTER COLUMN envelope SET STORAGE DEFAULT;