#!/bin/bash


# Change to script's directory
cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"

# Array of directories to process
declare -a dirs=("../sdk/src")

# Loop through each directory
for dir in "${dirs[@]}"; do
  # Change directory to the target
  cd "$dir" || { echo "Directory $dir does not exist, skipping..."; continue; }

  # Initialize an empty array to store export statements
  declare -a exports
  exports=()

  # Add a fun comment at the top
  echo "/**************************************************************************" > index.ts
  echo " * This file can be auto generated by 🏕️ scripts/generate_sdk_index.sh 🏕️ *" >> index.ts
  echo " **************************************************************************/" >> index.ts

  # Loop through each TypeScript file to append an export statement to the array
  # Skip files that have ".test." in their name, the existing index.ts file, and directories
  for file in $(find . -type f -name "*.ts" ! -name "*.test*" ! -name "*.d.ts" ! -name "index.ts" | sort); do
    # Remove the './' prefix and '.ts' suffix from the file path
    file=$(echo "$file" | sed "s|^\./||;s|\.ts$||")
    
    # Append export statement to the array
    exports+=("export * from './$file'")
  done

  echo "writing $dir/index.ts"

  # Append the sorted export statements to index.ts
  printf "%s\n" "${exports[@]}" >> index.ts

  # Change back to the original directory to continue the loop
  cd - || exit
done
