services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - '16686:16686'
            - '4317:4317'
            - '4318:4318'
        restart: always
        environment:
            - LOG_LEVEL=debug
