name: Network Diff Upgrade

on:
    workflow_dispatch:

jobs:
    Run_Alpha_to_Gamma:
        name: Run Alpha to Gamma Diff Upgrade
        uses: ./.github/workflows/Bytecode_diff_report.yml
        with:
            origin_environment: alpha
            target_environment: gamma
        secrets:
            BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
            BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
            BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
            BASESCAN_SEPOLIA_API_KEY: ${{ secrets.BASESCAN_SEPOLIA_API_KEY }}
            BLOCKSCOUT_BASE_SEPOLIA_API_KEY: ${{ secrets.BLOCKSCOUT_BASE_SEPOLIA_API_KEY }}
            GAMMA_BASE_SEPOLIA_DEPLOYER_PK: ${{ secrets.GAMMA_BASE_SEPOLIA_DEPLOYER_PK }}
            RIVER_S3_AWS_ACCESS_KEY_ID: ${{ secrets.RIVER_S3_AWS_ACCESS_KEY_ID }}
            RIVER_S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.RIVER_S3_AWS_SECRET_ACCESS_KEY }}
            RIVER_S3_AWS_REGION: ${{ secrets.RIVER_S3_AWS_REGION }}
