name: Network Diff Upgrade

on:
    workflow_dispatch:

jobs:
    Run_Alpha_to_Gamma:
        name: Run Alpha to Gamma Diff Upgrade
        uses: ./.github/workflows/Bytecode_diff_report.yml
        with:
            origin_environment: alpha
            target_environment: gamma
