name: Network Diff Upgrade

on:
    workflow_dispatch:

jobs:
    diff_report:
        name: Gamma Network Diff Report
        uses: ./.github/workflows/Bytecode_diff_report.yml
        secrets: inherit
        with:
          origin_environment: alpha
          target_environment: gamma
    
    upgrade_gamma_facets:
        name: Upgrade Gamma Facets
        needs: diff_report
        uses: ./.github/workflows/Upgrade_network_facets.yml
        secrets: inherit
        with:
            environment_name: gamma
