name: Render Diff Upgrade Report
env:
    BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
    BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
    REPORT_OUT_DIR: ${{ vars.REPORT_OUT_DIR }}
    AWS_ACCESS_KEY_ID: ${{ secrets.RIVER_S3_AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.RIVER_S3_AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.RIVER_S3_AWS_REGION }}
    GOWORK: off

on:
    workflow_dispatch:
        inputs:
            environment_name:
                description: 'Environment name'
                required: true
                type: choice
                options:
                    - 'alpha'
                    - 'gamma'
                    - 'omega'

    workflow_call:
        inputs:
            environment_name:
                description: 'Environment name'
                required: true
                type: string

jobs:
    Render_Diff_Upgrade_Report:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.22' # Specify the Go version you need

            - name: Install dependencies
              run: |
                  go mod download
                  go mod tidy
              working-directory: scripts/bytecode-diff

            - name: Get latest facet diff file
              run: |
                  FACET_DIFF_FILE=$(find ${{ env.REPORT_OUT_DIR }} -name "facet_diff*.yaml" | sort -r | head -n 1)
                  echo "Latest facet diff file: $FACET_DIFF_FILE"
                  echo "FACET_DIFF_FILE=$FACET_DIFF_FILE" >> $GITHUB_ENV

            - name: Run final html report generation w/ updated hashes
              id: gen_html_report
              run: |
                  go run main.go add-hashes ${{ inputs.environment_name }} ${{ env.FACET_DIFF_FILE }}
              working-directory: scripts/bytecode-diff

            - name: Configure AWS credentials
              if: steps.gen_html_report.outcome == 'success'
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Copy HTML report to S3
              if: steps.gen_html_report.outcome == 'success'
              run: |
                  # Find the latest hashed HTML file
                  HTML_FILE=$(find ${{ env.REPORT_OUT_DIR }} -name "*_hashed_*.html" | sort -r | head -n 1)

                  if [ -z "$HTML_FILE" ]; then
                    echo "Error: No hashed HTML file found"
                    exit 1
                  fi

                  echo "Latest hashed HTML file: $HTML_FILE"

                  # Copy to report.html
                  aws s3 cp $HTML_FILE s3://${{ inputs.environment_name }}-reports/report.html

                  # Copy to report_YYYYMMDD.html
                  DATED_FILENAME="report_$(date -u +%Y%m%d).html"
                  aws s3 cp $HTML_FILE s3://${{ inputs.environment_name }}-reports/$DATED_FILENAME

                  echo "HTML report copied to S3 bucket ${{ inputs.environment_name }}-reports files report.html and $DATED_FILENAME"
