[package]
name = "mls-lib"
edition.workspace = true

[dependencies]
river-mls = {workspace = true}
river-mls-protocol = {workspace = true}
libc = "0.2"
prost = {workspace = true}

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.27.0"
